apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: redis
      labels:
        app: myapp
        type: redis-pod
    spec:
      containers:
      - name: redis-container
        image: redis
  replicas: 3
  selector:
    matchLabels:
      type: redis-pod
