apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    name: result-app-pod
    app: demo-voting-app
spec:
  containers:
  - name: result-app
    image: kodekloud/examplevotingapp_result:v1 # from DockerHub: https://hub.docker.com/r/kodekloud/examplevotingapp_result/tags
    ports:
      - containerPort: 80
