apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    name: voting-app-pod
    app: demo-voting-app
spec:
  containers:
  - name: voting-app
    image: kodekloud/examplevotingapp_vote:v1 # from DockerHub: https://hub.docker.com/r/kodekloud/examplevotingapp_vote/tags
    ports:
      - containerPort: 80